Channel upgrade
datachainlab/yui-relayer-build pull request #35
Opened 2024-08-21 06:33 UTC by siburu

2024-09-17 04:41 UTC, dai1975 requested changes

2024-09-17 04:41 UTC, dai1975 commented on tests/chains/ethereum/contracts/scripts/deploy.js
> +    await proxyV1.proposeAppVersion(`mockapp-${i}`, {
test-channel-upgrade スクリプトで、
`$RLY eth upgrade propose` 
してるので、deploy.js 側では不要?

2024-09-17 12:15 UTC, siburu commented on tests/chains/ethereum/contracts/scripts/deploy.js
> +    await proxyV1.proposeAppVersion(`mockapp-${i}`, {
@dai1975 `$RLY eth upgrade propose` does not execute `proposeAppVersion` but executes `proposeUpgrade`.
This is a shortened version of `$RLY ethereum channel-upgrade propose-upgrade`.

2024-09-18 01:01 UTC, dai1975 approved these changes

2024-09-18 01:05 UTC, merged